services:
  funstats-api:
    build: .
    ports:
      - "5050:5050" # Map container port 3000 to host port 3000
    env_file:
      - .env
    depends_on:
      - mysql
    restart: on-failure
    networks:
      - express-network

  mysql:
    image: mysql:8
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306" # Map MySQL port
    volumes:
      - mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    restart: unless-stopped
    networks:
      - express-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8443:8443"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./ssl:/etc/ssl
    depends_on:
      - funstats-api
    networks:
      - express-network

volumes:
  mysql-data:

networks:
  express-network:
